name: local-llm

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ./llm_data/:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - local-llm-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

networks:
  local-llm-network:
