name: selfhost

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - "/media/vix/Extra SSD/LLM:/root/.ollama"
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
